'use strict';
const $=id=>document.getElementById(id);let token='',images=[],busy=false,timer=null;
function status(message){$('status').textContent=message;}
function lock(value){busy=value;$('controls').disabled=value;}
async function api(path,body){if(!token)throw Error('Avval ulanish kodini tekshir.');const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),90000);try{const response=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:controller.signal,redirect:'error',cache:'no-store'});let data;try{data=await response.json();}catch{throw Error('Server javobi o‘qilmadi (HTTP '+response.status+').');}if(!response.ok)throw Error(data.error||'Server xatosi: '+response.status);return data;}catch(e){if(e.name==='AbortError')throw Error('Javob kutilgan vaqtda kelmadi. Qayta yaratishdan oldin Ishlarimni tekshir.');throw e;}finally{clearTimeout(timeout);}}
function missing(health,body){const errors=[];if(!health.configured)errors.push('Video/rasm yaratish xizmati hali ulanmagan (fal.ai).');if((body.auto_text||body.video_language!=='none')&&!health.image_text)errors.push('Matn o‘qish va tarjima xizmati hali ulanmagan (Gemini).');if(body.video_language!=='none'&&!(health.voice_languages||[]).includes(body.video_language))errors.push('Tanlangan ovoz xizmati hali ulanmagan (Azure Speech).');if(body.kind!=='image'&&(body.duration==='30'||(body.images||[]).length>1||body.auto_text||body.video_language!=='none')&&!health.montage)errors.push('Video birlashtirish xizmati tayyor emas.');return errors;}
$('connect').onclick=async()=>{const candidate=$('token').value.trim();if(candidate.length<32||!/^[\x21-\x7e]+$/.test(candidate)){$('connectionStatus').textContent='Railway’dagi BEGBORIM_TOKEN qiymatini aynan nusxala. Tasdiqlash kodi yoki oddiy matn mos kelmaydi.';return;}token=candidate;$('connect').disabled=true;try{const h=await api('/health');$('badge').textContent='Server ulangan';$('connectionStatus').textContent=h.configured?'Server ulandi. Tanlangan rejim xizmatlari yaratishdan oldin tekshiriladi.':'Server ulandi. AI kalitlari hali qo‘shilmagan; hozircha video yaratib bo‘lmaydi.';await loadJobs();}catch(e){token='';$('badge').textContent='Ulanmagan';$('connectionStatus').textContent=e.message;}finally{$('connect').disabled=false;}};
$('disconnect').onclick=()=>{if(busy)return;token='';$('token').value='';$('badge').textContent='Ulanmagan';$('connectionStatus').textContent='Ulanish uzildi.';$('jobs').replaceChildren();clearTimeout(timer);};
$('kind').onchange=()=>{const image=$('kind').value==='image';$('imageArea').hidden=$('kind').value!=='image_video';for(const id of ['duration','language','camera'])$(id).disabled=image;};
$('idea').onclick=()=>{if($('prompt').value&&!confirm('Hozirgi tavsif mini ferma shabloni bilan almashtirilsinmi?'))return;$('prompt').value='A blue grain truck is stuck in shallow mud. A cheerful red mini tractor and yellow tracked excavator help it out. A green combine waits nearby. A little farmer boy and puppy watch safely behind a fence. Colorful cinematic 3D cartoon, consistent vehicle colors, happy ending, no text or logos.';};
async function convert(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error(file.name+': JPG, PNG yoki WebP tanlang.');if(file.size>30*1024*1024)throw Error(file.name+': fayl 30 MB dan katta.');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>50000000)throw Error(file.name+': rasm o‘lchami juda katta.');const scale=Math.min(1,2048/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);let quality=.86,data=canvas.toDataURL('image/jpeg',quality);while(data.length>2000000&&quality>.35){quality-=.1;data=canvas.toDataURL('image/jpeg',quality);}if(data.length>2000000)throw Error(file.name+': kichikroq rasm tanlang.');return {name:file.name,data};}finally{bitmap.close();}}
$('files').onchange=async()=>{const files=Array.from($('files').files);$('files').value='';if(images.length+files.length>15){status('Jami 15 tagacha rasm tanlash mumkin.');return;}lock(true);const errors=[];try{for(const file of files){try{images.push(await convert(file));}catch(e){errors.push(e.message);}}renderImages();status(errors.join('\n')||'Rasmlar tayyor. Hali serverga yuborilmadi.');}finally{lock(false);$('kind').onchange();}};
function renderImages(){$('count').textContent=images.length+' / 15 ta rasm';$('previews').replaceChildren();images.forEach((item,index)=>{const card=document.createElement('div');card.className='preview';const img=document.createElement('img');img.src=item.data;img.alt='Sahna '+(index+1);const caption=document.createElement('span');caption.textContent='Sahna '+(index+1);const actions=document.createElement('div');for(const [label,offset] of [['↑',-1],['↓',1],['×',0]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-label','Sahna '+(index+1)+' '+(offset<0?'oldinga':offset>0?'keyinga':'o‘chirish'));b.disabled=(offset<0&&index===0)||(offset>0&&index===images.length-1);b.onclick=()=>{if(busy)return;if(offset===0)images.splice(index,1);else [images[index],images[index+offset]]=[images[index+offset],images[index]];renderImages();};actions.append(b);}card.append(caption,img,actions);$('previews').append(card);});}
$('create').onsubmit=async event=>{event.preventDefault();if(busy)return;const kind=$('kind').value,auto=kind==='image_video'&&$('auto').checked;const original=$('prompt').value.trim();if(!auto&&original.length<3){status('Sahna tavsifini yoz.');return;}if(kind==='image_video'&&!images.length){status('Kamida bitta rasm tanla.');return;}const prompt=[original,kind!=='image'?$('camera').value:'',$('style').value,$('effect').value,$('consistent').checked?'Preserve reference faces, outfits, colors and proportions across scenes. Do not add new characters.':''].filter(Boolean).join('\n');if(prompt.length>2500){status('Tavsif va effektlar 2500 belgidan oshmasin.');return;}const body={id:crypto.randomUUID(),kind,prompt,ratio:$('ratio').value,duration:$('duration').value,auto_text:auto,video_language:kind==='image'?'none':$('language').value};if(kind==='image_video')body.images=images.map(i=>i.data);lock(true);status('AI xizmatlari tekshirilmoqda…');try{const h=await api('/health');const errors=missing(h,body);if(errors.length)throw Error(errors.join('\n'));const n=kind==='image_video'?images.length:1;const clips=n*Math.ceil(Number(body.duration)/n/10);if(!confirm((kind==='image'?'1 ta pulli rasm generatsiyasi.':body.duration+' soniyali video uchun '+clips+' ta pulli AI lavha yaratiladi.')+' Rasmlar va matn tegishli AI xizmatlariga yuboriladi. Boshlansinmi?')){status('Bekor qilindi.');return;}status('So‘rov yuborilmoqda. Qayta bosmang…');const job=await api('/jobs',body);status('So‘rov qabul qilindi. Holat: '+job.status);await loadJobs();}catch(e){status(e.message);}finally{lock(false);$('kind').onchange();}};
async function loadJobs(){clearTimeout(timer);if(!token)return;try{const result=await api('/jobs');$('jobs').replaceChildren();const jobs=result.jobs||[];$('jobsStatus').textContent=jobs.length?jobs.length+' ta ish. Faol ishlar avtomatik yangilanadi.':'Hali yaratilgan ish yo‘q.';let active=false;for(let job of jobs.slice(0,30)){if(['IN_QUEUE','IN_PROGRESS'].includes(job.status)){active=true;try{job=await api('/jobs/'+encodeURIComponent(job.id));}catch{}}const card=document.createElement('article');card.className='job';const heading=document.createElement('strong');heading.textContent=job.status+(job.stage?' · '+job.stage:'');const p=document.createElement('p');p.textContent=job.error||job.prompt||job.id;card.append(heading,p);if(job.url){try{const url=new URL(job.url);if(url.protocol==='https:'){const a=document.createElement('a');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Natijani ochish / yuklab olish ↗';card.append(a);}}catch{}}$('jobs').append(card);}if(active&&token)timer=setTimeout(loadJobs,10000);}catch(e){$('jobsStatus').textContent=e.message;}}
$('refresh').onclick=()=>{if(!busy)loadJobs();};
