'use strict';
const HF={model:'seedance25-i2v',params:{},files:{},paid:false,search:'',filter:'all',error:'',pending:null,board:[]};
const HF_EFFECTS=[
 ['Sekin yaqinlashish','The camera slowly dollies toward the subject. Natural body motion, physically plausible lighting.'],
 ['Atrofidan aylanish','A smooth 180 degree orbit around the subject. Preserve the reference identity and clothing.'],
 ['Kino yorug‘ligi','Warm cinematic sunset light, soft rim lighting, natural movement, fine film grain.'],
 ['Sehrli zarrachalar','Subtle luminous particles swirl gently around the subject as they react with wonder.'],
 ['Miniatyura dunyosi','A detailed miniature world with macro depth of field, tactile materials and gentle natural motion.'],
 ['Tabiiy portret','A subtle smile and a natural blink. Keep the same facial features and proportions.'],
 ['Mahsulot namoyishi','A premium product presentation, slow camera orbit, soft studio reflections and a clean background.'],
 ['Bolalar multfilmi','Original friendly 3D cartoon, bright playful colors, safe gentle actions and expressive faces.'],
 ['Yomg‘irli sahna','Soft rain falls, small puddles ripple and fabric moves naturally. Keep the reference subject consistent.'],
 ['Keng manzara','A slow crane shot reveals a wide beautiful landscape, consistent horizon and natural motion.'],
 ['Moda kadri','A confident slow walk, realistic fabric movement, clean editorial fashion lighting.'],
 ['Jonli bog‘','Flower petals drift in a gentle breeze; soft sunlight and calm continuous movement.']
];
function currentHF(){return window.SHIRIN_MODELS.find(m=>m.id===HF.model)||window.SHIRIN_MODELS[0];}
function hfDefaults(m){return Object.fromEntries(m.fields.filter(f=>f.default!==undefined).map(f=>[f.key,f.default]));}
let hfSaveTimer;
function saveHF(){clearTimeout(hfSaveTimer);hfSaveTimer=setTimeout(()=>dbPut('meta',{model:HF.model,params:HF.params,files:HF.files,pending:HF.pending,board:HF.board},'hfDraft').catch(()=>toast('Qoralama saqlanmadi. Xotirani tekshir.')),150);}
async function loadHiggsfieldDraft(){const d=await dbGet('meta','hfDraft');if(d){for(const k of ['model','params','files','pending','board'])if(d[k]!==undefined)HF[k]=d[k];}else HF.params=hfDefaults(currentHF());HF.paid=false;}
function selectHF(id){if(S.busy)throw Error('Avvalgi ish tugashini kut.');const m=window.SHIRIN_MODELS.find(x=>x.id===id);if(!m)return;if(id===HF.model){go('studio');return;}const text=HF.params.prompt||S.form.prompt||'';HF.model=id;HF.params={...hfDefaults(m),prompt:text};HF.paid=false;HF.error='';saveHF();go('studio');}
NAV.splice(0,NAV.length,...[['home','Bosh'],['studio','Yaratish'],['models','Modellar'],['effects','Effektlar'],['canvas','Storyboard'],['image','Rasm tahriri'],['montage','Rasm montaji'],['edit','Video tahriri'],['voice','Ovoz'],['chat','AI yordamchi'],['gallery','Galereya'],['templates','G‘oyalar'],['settings','Sozlamalar']]);
PATHS.studio=PATHS.spark;PATHS.models=PATHS.templates;PATHS.effects=PATHS.spark;PATHS.canvas=PATHS.templates;PATHS.montage=PATHS.video;
nav=function(){const primary=[['home','Bosh'],['studio','Yaratish'],['models','Modellar'],['effects','Effektlar'],['canvas','Storyboard'],['voice','Ovoz'],['gallery','Galereya']];$('navigation').innerHTML=primary.map(([n,t])=>`<button class="nav-button ${S.page===n?'active':''}" data-page="${n}">${icon(n)}<span>${t}</span></button>`).join('')+`<button class="nav-button more-nav" data-action="more-tools">${icon('templates')}<span>Yana</span></button>`;};
const originalGo=go;
go=function(page){if(page==='video'){if(S.form.prompt)HF.params.prompt=S.form.prompt;page='studio';}if(page==='montage')S.form.engine='browser';originalGo(page);};
const originalRender=render;
render=function(){originalRender();const e=$('headerConnection');if(e){e.textContent=S.health?.higgsfield?.configured&&S.connected?'AI sozlangan':S.connected?'Server ulangan':'Shaxsiy studiya';e.classList.toggle('ready',!!S.connected);}};
home=function(){return `<section class="sh-hero"><div class="hero-lines" aria-hidden="true"><i></i><i></i><i></i><i></i></div><div class="eyebrow">SHIRIN / SENGA TEGISHLI IJOD MAYDONI</div><h1>G‘oyangni<br><em>jonlantir.</em></h1><p>Rasmdan harakatga. Matndan tasvirga.<br>Yaratish, tahrirlash va saqlash — bitta studiyada.</p><div class="actions"><button class="primary" data-page="studio">Yaratishni boshlash ${icon('arrow')}</button><button class="secondary" data-page="gallery">Mening ishlarim</button></div><span class="hero-foot">IMAGE · VIDEO · AUDIO · EDIT</span></section><div class="section-head"><div><span class="eyebrow">CREATIVE TOOLS</span><h2>Bugun nima yaratamiz?</h2></div><button class="text-button" data-action="more-tools">Barcha vositalar ↗</button></div><div class="sh-feature-grid">${[['studio','Rasmni jonlantirish','Seedance va Kling','01','lime'],['image','Rasm bilan ishlash','Rang, nisbat, fon','02','pink'],['effects','Harakat va uslub','12 ta tayyor tavsif','03','blue'],['canvas','Hikoyani rejalash','Kadrlar va sahnalar','04','sand']].map(([p,t,d,n,c])=>`<button class="sh-feature ${c}" data-page="${p}"><span class="feature-number">${n}</span><div class="feature-symbol">${icon(p)}</div><strong>${t}</strong><small>${d}</small><span class="feature-arrow">↗</span></button>`).join('')}</div><div class="section-head"><div><span class="eyebrow">MODEL LIBRARY</span><h2>AI studiyang</h2></div><button class="text-button" data-page="models">Barchasini ko‘rish →</button></div><div class="sh-model-grid">${window.SHIRIN_MODELS.slice(0,4).map(modelCard).join('')}</div><section class="sh-connect"><div>${icon('settings')}<div><strong>${S.health?.higgsfield?.configured?'Higgsfield API sozlangan':'AI xizmatini ulash'}</strong><p>${S.health?.higgsfield?.configured?'Model hisobining ruxsati va balansi generatsiya vaqtida tekshiriladi.':'Haqiqiy AI yaratish uchun o‘z servering va Higgsfield API hisobi kerak.'}</p></div></div><button class="secondary" data-page="settings">${S.connected?'Holatni ko‘rish':'Ulanishni sozlash'}</button></section><footer><span>shirin · 0.1.1</span><span>Mustaqil ijod studiyasi</span></footer>`;};
function modelCard(m){return `<button class="sh-model" data-hf-model="${esc(m.id)}"><span class="model-badge">${icon(m.type==='video'?'video':'image')}</span><span class="model-copy"><strong>${esc(m.name)}</strong><small>${esc(m.mode)}</small></span><span class="model-type">${m.type==='video'?'VIDEO':'RASM'}</span></button>`;}
function modelsPage(){const rows=window.SHIRIN_MODELS.filter(m=>(HF.filter==='all'||m.type===HF.filter)&&(m.name+' '+m.mode).toLowerCase().includes(HF.search.toLowerCase()));return `${head('Model kutubxonasi','Hujjat asosida qo‘shilgan ulanishlar. Haqiqiy foydalanish API hisobingga bog‘liq.')}<div class="filterbar">${[['all','Barchasi'],['video','Video'],['image','Rasm']].map(([k,t])=>`<button data-hf-filter="${k}" class="${HF.filter===k?'active':''}">${t}</button>`).join('')}<input id="hfSearch" type="search" placeholder="Model yoki vazifani qidirish" aria-label="Model qidirish" value="${esc(HF.search)}"></div><div class="sh-model-grid">${rows.length?rows.map(modelCard).join(''):'<p class="muted">Mos model topilmadi.</p>'}</div><p class="hint mt">Ulanishlar: ${window.SHIRIN_MODELS.length}. Bu Higgsfield saytining to‘liq katalogi emas. Model tanlanganda uning qo‘llaydigan parametrlari ochiladi.</p>`;}
function hfField(f){const v=HF.params[f.key]??f.default??'';if(['image','video','images'].includes(f.type)){const files=HF.files[f.key]||[];return `<section class="hf-upload"><div class="small-title">${esc(f.label)}${f.required?' *':''}</div><label class="upload-zone">${icon('upload')}<strong>${files.length?files.length+' ta fayl tanlangan':'Fayl tanlash'}</strong><small>${f.type==='video'?'MP4 · 128 MB gacha':'Telefon galereyasi · PNG, JPG, WebP'}</small><input data-hf-file="${f.key}" type="file" accept="${f.type==='video'?'video/mp4':'image/png,image/jpeg,image/webp'}" ${f.type==='images'?'multiple':''}></label>${files.length?`<div class="hf-files">${files.map((x,i)=>`<div>${f.type==='video'?`<video src="${blobURL(x.blob)}" controls playsinline preload="metadata"></video>`:`<img src="${blobURL(x.blob)}" alt="Reference ${i+1}">`}<small>${esc(x.name)}</small><button data-hf-remove="${f.key}" data-index="${i}" aria-label="Faylni olib tashlash">×</button></div>`).join('')}</div>`:''}</section>`;}
 if(f.type==='boolean')return `<label class="check"><input type="checkbox" data-hf-field="${f.key}" ${v?'checked':''}> ${esc(f.label)}</label>`;
 if(f.type==='select')return `<label>${esc(f.label)}<select data-hf-field="${f.key}">${f.options.map(o=>`<option value="${esc(o)}" ${String(v)===String(o)?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;
 if(f.type==='number')return `<label>${esc(f.label)}<input data-hf-field="${f.key}" type="number" value="${esc(v)}" ${f.min!==undefined?'min="'+f.min+'"':''} ${f.max!==undefined?'max="'+f.max+'"':''} step="${f.step||1}" placeholder="${f.options?'Variantlar: '+f.options.join(', '):''}"></label>`;
 return `<label>${esc(f.label)}${f.required?' *':''}<textarea data-hf-field="${f.key}" maxlength="10000" placeholder="${f.key==='prompt'?'Nima yaratamiz? Harakat, qahramon va muhitni tasvirla…':'Ixtiyoriy'}">${esc(v)}</textarea></label>`;
}
function studioPage(){const m=currentHF(),configured=S.connected&&S.health?.higgsfield?.configured;return `${head('Yaratish studiyasi','G‘oyangni yoz, reference qo‘sh va modelingni tanla.')}<div class="hf-layout"><section class="panel hf-form"><div class="hf-model-head"><span class="model-badge">${icon(m.type==='video'?'video':'image')}</span><div><strong>${esc(m.name)}</strong><small>${esc(m.mode)}</small></div><button class="text-button" data-action="hf-model-picker">Almashtirish ↓</button></div><div class="hf-fields">${m.fields.map(hfField).join('')}</div><div class="hf-submit">${HF.error?`<div class="connection-note" role="alert">${esc(HF.error)}</div>`:''}${configured?`<label class="check"><input type="checkbox" id="hfPaid" ${HF.paid?'checked':''}> Bu generatsiya Higgsfield API balansidan to‘lanishiga roziman.</label><p class="hint">Narx model va parametrga bog‘liq. <a href="${esc(m.source)}" target="_blank" rel="noopener noreferrer">Rasmiy tarif va parametrlar ↗</a></p><button class="primary full" data-action="${HF.pending?'hf-recover':'hf-generate'}" ${S.busy?'disabled':''}>${icon('spark')} ${HF.pending?'Oxirgi so‘rovni tekshirish':S.busy?'Tayyorlanmoqda…':'Yaratish'}</button>`:`<div class="connection-note"><strong>AI ulanishi kerak</strong><p>${S.connected?'Serverda Higgsfield API kaliti hali sozlanmagan.':'Shirin serveriga ulan. Tanlangan rasmlar va tavsif qoralamada saqlanadi.'}</p><button class="primary full" data-page="settings">Ulanishni sozlash →</button></div>`}</div></section><aside class="hf-guide"><div class="sh-poster"><span>SHIRIN STUDIO</span><div>${m.type==='video'?'MOTION':'IMAGINE'}<em>starts here.</em></div><span>${esc(m.name)} / ${esc(m.mode)}</span></div><section class="panel"><h3>Yaxshi natija uchun</h3><ol><li>Aniq va sifatli reference tanla.</li><li>Bir sahnadagi asosiy harakatni yoz.</li><li>Avval qisqa video bilan sinab ko‘r.</li></ol><p class="hint">AI natijasi modelga bog‘liq. Shirin rasm montajini AI jonlantirish deb ko‘rsatmaydi.</p><button class="secondary full" data-page="effects">Harakat tavsifini tanlash</button></section></aside></div>`;}
function effectsPage(){return `${head('Harakat va effekt g‘oyalari','Tanlov tavsifga qo‘shiladi. Natijani tanlangan AI modeli yaratadi.')}<div class="effects-grid">${HF_EFFECTS.map(([name,text],i)=>`<button class="effect-card tone-${i%4}" data-effect-index="${i}"><span>${String(i+1).padStart(2,'0')}</span><div>${icon('spark')}</div><strong>${name}</strong><small>Tavsifga qo‘shish ↗</small></button>`).join('')}</div>`;}
function canvasPage(){return `${head('Storyboard','Kadrlarni rejalashtir, tartibla va har birini yaratish studiyasiga yubor.')}<div class="actions"><button class="primary" data-action="board-add">+ Yangi kadr</button><button class="secondary" data-action="board-export">Storyboardni yuklash</button></div><div class="board-grid mt">${HF.board.length?HF.board.map((x,i)=>`<section class="board-card"><div class="section-head"><strong>KADR ${String(i+1).padStart(2,'0')}</strong><div><button data-board-move="${i}" data-dir="-1" ${i===0?'disabled':''} aria-label="Oldinga">←</button><button data-board-move="${i}" data-dir="1" ${i===HF.board.length-1?'disabled':''} aria-label="Keyinga">→</button></div></div><textarea data-board-id="${x.id}" placeholder="Bu kadrda nima bo‘ladi?">${esc(x.prompt)}</textarea><div class="actions"><button class="secondary" data-board-use="${x.id}">Studiyada ochish →</button><button class="danger" data-board-delete="${x.id}" aria-label="Kadrni o‘chirish">×</button></div></section>`).join(''):'<section class="panel empty">Birinchi kadrni qo‘shib hikoyangni rejalashni boshla.</section>'}</div>`;}
videoSetupDetails=function(){const ready=S.connected&&S.health?.higgsfield?.configured;return `<section class="note ${ready?'':'amber'}"><strong>${ready?'Higgsfield API kaliti sozlangan':'AI ulanishi kerak'}</strong><p>${ready?'Model ruxsati va hisob balansi generatsiya vaqtida tekshiriladi.':'Haqiqiy rasm va video yaratish uchun Shirin serverida Higgsfield API kalitini sozla.'}</p></section>`;};
const oldSettings=settingsPage;
settingsPage=function(){let html=oldSettings();const hf=S.health?.higgsfield;return html.replace('<h2>Serverga ulanish</h2>','<h2>Shirin serveriga ulanish</h2><p class="hint">Tayyor ulanish faylini tanla yoki server manzili va shaxsiy kodingni kirit.</p>')+`<section class="panel mt"><h2>Higgsfield API</h2><p class="muted">${hf?.configured?'Kalit serverda sozlangan. Hisob, model ruxsati va balans hali jonli generatsiya bilan tekshirilmagan.':'Haqiqiy AI rasm va video yaratish uchun serverga Higgsfield API kaliti ulanishi kerak.'}</p><a class="file-button mt" href="https://open.higgsfield.ai/" target="_blank" rel="noopener noreferrer">API hisobini ochish ↗</a><p class="hint mt">Saytdagi obuna va API balansi alohida. Shirin Higgsfieldning rasmiy ilovasi emas. Yopiq kod, xususiy model va xizmatlar Shirin mulkiga aylanmaydi.</p></section>`;};
async function hfSubmit(recover=false){
 if(S.busy)throw Error('Avvalgi ish tugashini kut.');
 if(!S.connected||!S.health?.higgsfield?.configured)throw Error('Avval Shirin serveri va Higgsfield API ulanishini sozla.');
 const m=currentHF();let body;
 if(!recover){
  if(HF.pending)throw Error('Avval oxirgi so‘rovni tekshir.');
  if(!HF.paid)throw Error('AI xarajatiga rozilikni belgila.');
  const params={};
  for(const f of m.fields){let v=HF.params[f.key];
   if(['image','video','images'].includes(f.type)){const files=HF.files[f.key]||[];if(f.required&&!files.length)throw Error(f.label+' kerak.');if(files.length){if(files.length>f.max_items&&f.type==='images')throw Error('Ko‘pi bilan '+f.max_items+' ta rasm tanla.');const values=await Promise.all(files.map(x=>fileData(x.blob)));v=f.type==='images'?values:values[0];}}
   if(v===undefined||v===null||v===''){if(f.required)throw Error(f.label+' kerak.');continue;}
   if(f.type==='number'&&(!Number.isFinite(v)||(f.min!==undefined&&v<f.min)||(f.max!==undefined&&v>f.max)||(f.options&&!f.options.includes(v))))throw Error(f.label+' qiymatini tekshir.');
   params[f.key]=v;
  }
  body={id:id(),kind:'hf_'+m.type,hf_model:m.id,hf_params:params,prompt:params.prompt||m.name,allow_paid:true,...(m.type==='video'?{video_intent:'animation'}:{})};
  HF.pending={id:body.id,model:m.id};await dbPut('meta',{model:HF.model,params:HF.params,files:HF.files,pending:HF.pending,board:HF.board},'hfDraft');
 }
 S.busy=true;S.cancel=false;HF.error='';task(recover?'So‘rov holati tekshirilmoqda…':'AI ga yuborilmoqda…');render();
 let job;
 try{
  job=recover?await api('/jobs/'+HF.pending.id):await api('/jobs',body);
  if(!['hf_video','hf_image'].includes(job.kind))throw Error('Server kutilmagan turdagi natija qaytardi.');
  job=await pollJob(job);if(!job){HF.pending=null;return;}
  if(!['hf_video','hf_image'].includes(job.kind))throw Error('AI natija turi mos emas.');
  await importJob(job);HF.pending=null;HF.paid=false;go('gallery');
 }catch(e){
  if(e.status>=400&&e.status<500)HF.pending=null;
  else if(job&&['FAILED','CANCELLED','INTERRUPTED'].includes(job.status))HF.pending=null;
  HF.error=e.message;throw e;
 }finally{endTask();saveHF();render();}
}
document.addEventListener('input',e=>{const el=e.target;if(el.dataset.hfField){HF.params[el.dataset.hfField]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:Number(el.value)):el.value;saveHF();}if(el.id==='hfPaid')HF.paid=el.checked;if(el.id==='hfSearch'){HF.search=el.value;render();$('hfSearch')?.focus();}if(el.dataset.boardId){const item=HF.board.find(x=>x.id===el.dataset.boardId);if(item){item.prompt=el.value;saveHF();}}});
document.addEventListener('change',async e=>{const el=e.target;if(!el.dataset.hfFile)return;try{if(S.busy)throw Error('Ish tugashini kut.');const f=currentHF().fields.find(x=>x.key===el.dataset.hfFile),files=Array.from(el.files||[]);if(files.length>(f.max_items||1))throw Error('Ko‘pi bilan '+(f.max_items||1)+' ta fayl tanla.');for(const x of files){if(x.size>128*1024*1024)throw Error('Fayl 128 MB dan katta.');if(f.type==='video'?x.type!=='video/mp4':!['image/png','image/jpeg','image/webp'].includes(x.type))throw Error('Mos rasm yoki MP4 fayl tanla.');}HF.files[f.key]=files.map(x=>({blob:x,name:x.name}));saveHF();render();}catch(x){toast(x.message);}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.dataset.hfModel)return selectHF(b.dataset.hfModel);
 if(b.dataset.hfFilter){HF.filter=b.dataset.hfFilter;render();return;}
 if(b.dataset.hfRemove){HF.files[b.dataset.hfRemove].splice(Number(b.dataset.index),1);saveHF();render();return;}
 if(b.dataset.effectIndex!==undefined){HF.params.prompt=[HF.params.prompt,HF_EFFECTS[Number(b.dataset.effectIndex)][1]].filter(Boolean).join('\n');saveHF();go('studio');return;}
 if(b.dataset.boardMove!==undefined){const i=Number(b.dataset.boardMove),j=i+Number(b.dataset.dir);if(HF.board[j])[HF.board[i],HF.board[j]]=[HF.board[j],HF.board[i]];saveHF();render();return;}
 if(b.dataset.boardUse){HF.params.prompt=HF.board.find(x=>x.id===b.dataset.boardUse).prompt;saveHF();go('studio');return;}
 if(b.dataset.boardDelete){if(confirm('Bu kadr o‘chirilsinmi?')){HF.board=HF.board.filter(x=>x.id!==b.dataset.boardDelete);saveHF();render();}return;}
 switch(b.dataset.action){
 case 'hf-model-picker':sheet('Model tanlash','<div class="sh-model-grid picker-grid">'+window.SHIRIN_MODELS.map(modelCard).join('')+'</div>');break;
 case 'hf-generate':await hfSubmit();break;
 case 'hf-recover':await hfSubmit(true);break;
 case 'board-add':HF.board.push({id:id(),prompt:''});saveHF();render();break;
 case 'board-export':await download(new Blob([JSON.stringify({format:'shirin-storyboard',version:1,frames:HF.board},null,2)],{type:'application/json'}),'Shirin-storyboard.json');break;
 }
 }catch(x){HF.error=x.message;if(S.page==='studio')render();toast(x.message);}});
